name: instrument_panel
description: House of Rooves application.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  home_automation_tools:
    git: git://github.com/Hixie/dart-home-automation-tools.git
  material_design_icons_flutter: any
  # dependency_overrides:
  # home_automation_tools:
  # path: ../../dart-home-automation-tools/
flutter:
  uses-material-design: true
  assets:
   - images/drawer_header.jpeg
   - credentials.cfg
   - ca.cert.pem
